# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LongTermGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goaltext', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='longtermgoal',
            name='operational_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.OperationalArea'),
        ),
        migrations.AddField(
            model_name='goal',
            name='long_term_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.LongTermGoal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.OperationalPlan'),
        ),
    ]
