# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verksamhetsplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('operational_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.OperationalArea')),
            ],
        ),
        migrations.RemoveField(
            model_name='longtermgoal',
            name='operational_area',
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='longtermgoal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='longtermgoal',
            name='sub_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.SubArea'),
            preserve_default=False,
        ),
    ]
