# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verksamhetsplan', '0002_auto_20170824_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verksamhetsplan.Status'),
        ),
        migrations.AddField(
            model_name='status',
            name='colour',
            field=models.CharField(default='#90C048', max_length=7),
            preserve_default=False,
        ),
    ]
