# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verksamhetsplan', '0003_auto_20170825_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='colour',
            new_name='color',
        ),
        migrations.AddField(
            model_name='longtermgoal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verksamhetsplan.Status'),
        ),
    ]
