# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 23:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verksamhetsplan', '0004_auto_20170825_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goal',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='verksamhetsplan.Goal')),
                ('long_term_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='verksamhetsplan.LongTermGoal')),
            ],
        ),
    ]
