# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 00:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('verksamhetsplan', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='verksamhetsplan.Goal'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='long_term_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='verksamhetsplan.LongTermGoal'),
        ),
    ]
