# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('verksamhetsplan', '0006_auto_20170829_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
