# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('verksamhetsplan', '0007_auto_20170829_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermgoal',
            name='status',
        ),
    ]
