# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 00:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('verksamhetsplan', '0008_remove_longtermgoal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='suggested_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='verksamhetsplan.Status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
